# Generated by Django 5.2 on 2025-04-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'ordering': ['uid']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['uid']},
        ),
        migrations.AlterModelOptions(
            name='hotelbooking',
            options={'ordering': ['uid']},
        ),
        migrations.AlterModelOptions(
            name='hotelimages',
            options={'ordering': ['uid']},
        ),
    ]
