# Generated by Django 5.2 on 2025-04-30 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hotelbooking_status_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='room_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
