# Generated by Django 5.2 on 2025-04-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_hotelbooking_room_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carte'), ('cash', 'Espèces'), ('transfer', 'Virement')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
