# Generated by Django 5.2 on 2025-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_hotelbooking_admin_notes_hotelbooking_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='admin_notes',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Payé'), ('failed', 'Échoué')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('mastercard', 'Mastercard')], max_length=20, null=True),
        ),
    ]
