# Generated by Django 5.2 on 2025-04-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_hotelbooking_admin_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('completed', 'Payé et Confirmé'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
