# Generated by Django 5.2 on 2025-04-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_hotelbooking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('mastercard', 'Mastercard')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
